export const dubaiareadata1 = [
    { label: 'Al Barsha', value: 'Al Barsha' },
    { label: 'Dubai Marina', value: 'Dubai Marina' },
    { label: 'Downtown Dubai', value: 'Downtown Dubai' },
    { label: 'Emirates Hills', value: 'Emirates Hills' },
    { label: 'Jebal Ali', value: 'Jebal Ali' },
    { label: 'Palm Jumeirah', value: 'Palm Jumeirah' },
    { label: 'Jumeirah Village Circle', value: 'Jumeirah Village Circle' },
    { label: 'Jumeirah Village Triangle', value: 'Jumeirah Village Triangle' },
    { label: 'Nad Al Sheba', value: 'Nad Al Sheba' },
];
export const dubaiareadata = [
    { label: "Acacia Avenues", value: "Acacia Avenues"  },
    { label: "Academic City", value: "Academic City"  },
    { label: "Akoya (DAMAC Hills)", value: "Akoya (DAMAC Hills)"  },
    { label: "Al Ameera Village", value: "Al Ameera Village"  },
    { label: "Al Aweer", value: "Al Aweer"  },
    { label: "Al Badaa", value: "Al Badaa"  },
    { label: "Al Barari", value: "Al Barari"  },
    { label: "Al Barsha", value: "Al Barsha"  },
    { label: "Al Furjan", value: "Al Furjan"  },
    { label: "Al Garhoud", value: "Al Garhoud"  },
    { label: "Al Hamriya", value: "Al Hamriya"  },
    { label: "Al Humaid City", value: "Al Humaid City"  },
    { label: "Al Ittihad Village", value: "Al Ittihad Village"  },
    { label: "Al Jaddaf", value: "Al Jaddaf"  },
    { label: "Al Jafiliya", value: "Al Jafiliya"  },
    { label: "Al Karama", value: "Al Karama"  },
    { label: "Al Khail Heights", value: "Al Khail Heights"  },
    { label: "Al Khawaneej", value: "Al Khawaneej"  },
    { label: "Al Kifaf", value: "Al Kifaf"  },
    { label: "Al Lisaili", value: "Al Lisaili"  },
    { label: "Al Mamzar", value: "Al Mamzar"  },
    { label: "Al Manara", value: "Al Manara"  },
    { label: "Al Mina", value: "Al Mina"  },
    { label: "Al Mizhar", value: "Al Mizhar"  },
    { label: "Al Nahda", value: "Al Nahda"  },
    { label: "Al Nahda 1", value: "Al Nahda 1"  },
    { label: "Al Nahda 2", value: "Al Nahda 2"  },
    { label: "Al Quoz", value: "Al Quoz"  },
    { label: "Al Qusais", value: "Al Qusais"  },
    { label: "Al Rashidiya", value: "Al Rashidiya"  },
    { label: "Al Rigga", value: "Al Rigga"  },
    { label: "Al Safa", value: "Al Safa"  },
    { label: "Al Sufouh", value: "Al Sufouh"  },
    { label: "Al Twar", value: "Al Twar"  },
    { label: "Al Warqaa", value: "Al Warqaa"  },
    { label: "Al Warsan", value: "Al Warsan"  },
    { label: "Al Wasl", value: "Al Wasl"  },
    { label: "Arabian Ranches", value: "Arabian Ranches"  },
    { label: "Arabian Ranches 2", value: "Arabian Ranches 2"  },
    { label: "Arabian Ranches 3", value: "Arabian Ranches 3"  },
    { label: "Arjan", value: "Arjan"  },
    { label: "Awali City", value: "Awali City"  },
    { label: "Barsha Heights(Tecom)", value: "Barsha Heights(Tecom)"  },
    { label: "Bawadi", value: "Bawadi"  },
    { label: "Bluewaters Island", value: "Bluewaters Island"  },
    { label: "Bur Dubai", value: "Bur Dubai"  },
    { label: "Business Bay", value: "Business Bay"  },
    { label: "City Of Arabia", value: "City Of Arabia"  },
    { label: "City Walk", value: "City Walk"  },
    { label: "Culture Village", value: "Culture Village"  },
    { label: "Damac Hills 2", value: "Damac Hills 2"  },
    { label: "Damac Lagoons", value: "Damac Lagoons"  },
    { label: "Deira", value: "Deira"  },
    { label: "Delma Street", value: "Delma Street"  },
    { label: "DIFC", value: "DIFC"  },
    { label: "Discovery Gardens", value: "Discovery Gardens"  },
    { label: "Downtown Dubai", value: "Downtown Dubai"  },
    { label: "Downtown Jebel Ali", value: "Downtown Jebel Ali"  },
    { label: "Dubai Airport Freezone(DAFZA)", value: "Dubai Airport Freezone(DAFZA)"  },
    { label: "Dubai Creek Club Residences", value: "Dubai Creek Club Residences"  },
    { label: "Dubai Creek Harbour", value: "Dubai Creek Harbour"  },
    { label: "Dubai Design District", value: "Dubai Design District"  },
    { label: "Dubai Festival City", value: "Dubai Festival City"  },
    { label: "Dubai Harbour", value: "Dubai Harbour"  },
    { label: "Dubai Healthcare City", value: "Dubai Healthcare City"  },
    { label: "Dubai Healthcare City 2", value: "Dubai Healthcare City 2"  },
    { label: "Dubai Hills Estate", value: "Dubai Hills Estate"  },
    { label: "Dubai Industrial City", value: "Dubai Industrial City"  },
    { label: "Dubai Internet City", value: "Dubai Internet City"  },
    { label: "Dubai Investment Park", value: "Dubai Investment Park"  },
    { label: "Dubai Lifestyle City", value: "Dubai Lifestyle City"  },
    { label: "Dubai Marina", value: "Dubai Marina"  },
    { label: "Dubai Maritime City", value: "Dubai Maritime City"  },
    { label: "Dubai Media City", value: "Dubai Media City"  },
    { label: "Dubai Pearl", value: "Dubai Pearl"  },
    { label: "Dubai Promenade", value: "Dubai Promenade"  },
    { label: "Dubai Residence Complex", value: "Dubai Residence Complex"  },
    { label: "Dubai Science Park", value: "Dubai Science Park"  },
    { label: "Dubai South City", value: "Dubai South City"  },
    { label: "Dubai Studio City", value: "Dubai Studio City"  },
    { label: "Dubai Waterfront", value: "Dubai Waterfront"  },
    { label: "Dubai World Central", value: "Dubai World Central"  },
    { label: "Dubailand", value: "Dubailand"  },
    { label: "EMAAR Beachfront", value: "EMAAR Beachfront"  },
    { label: "Emirates Golf Club", value: "Emirates Golf Club"  },
    { label: "Emirates Hills", value: "Emirates Hills"  },
    { label: "Emirates Living", value: "Emirates Living"  },
    { label: "Falcon City Of Wonders", value: "Falcon City Of Wonders"  },
    { label: "Frond A", value: "Frond A"  },
    { label: "Frond B", value: "Frond B"  },
    { label: "Frond C", value: "Frond C"  },
    { label: "Frond D", value: "Frond D"  },
    { label: "Golf City", value: "Golf City"  },
    { label: "Green Community", value: "Green Community"  },
    { label: "Greens", value: "Greens"  },
    { label: "IMPZ", value: "IMPZ"  },
    { label: "International City", value: "International City"  },
    { label: "JBR", value: "JBR"  },
    { label: "Jebel Ali", value: "Jebel Ali"  },
    { label: "Jumeirah", value: "Jumeirah"  },
    { label: "Jumeirah Golf Estates", value: "Jumeirah Golf Estates"  },
    { label: "Jumeirah Heights", value: "Jumeirah Heights"  },
    { label: "Jumeirah Hills", value: "Jumeirah Hills"  },
    { label: "Jumeirah Islands", value: "Jumeirah Islands"  },
    { label: "Jumeirah Lake Towers", value: "Jumeirah Lake Towers"  },
    { label: "Jumeirah Park", value: "Jumeirah Park"  },
    { label: "Jumeirah Village Circle", value: "Jumeirah Village Circle"  },
    { label: "Jumeirah Village Triangle", value: "Jumeirah Village Triangle"  },
    { label: "Living Legends", value: "Living Legends"  },
    { label: "Liwan", value: "Liwan"  },
    { label: "Majan", value: "Majan"  },
    { label: "Meadows", value: "Meadows"  },
    { label: "Meydan", value: "Meydan"  },
    { label: "Meydan Avenue", value: "Meydan Avenue"  },
    { label: "Mina Rashid", value: "Mina Rashid"  },
    { label: "Mira Oasis", value: "Mira Oasis"  },
    { label: "Mirdif", value: "Mirdif"  },
    { label: "Mizin", value: "Mizin"  },
    { label: "Mohammad Bin Rashid City", value: "Mohammad Bin Rashid City"  },
    { label: "Motor City", value: "Motor City"  },
    { label: "Mudon", value: "Mudon"  },
    { label: "Muhaisnah", value: "Muhaisnah"  },
    { label: "Nad Al Sheba", value: "Nad Al Sheba"  },
    { label: "Nadd Al Hammar", value: "Nadd Al Hammar"  },
    { label: "Old Town", value: "Old Town"  },
    { label: "Other", value: "Other"  },
    { label: "Oud Al Muteena", value: "Oud Al Muteena"  },
    { label: "Oud Metha", value: "Oud Metha"  },
    { label: "Palm Jebel Ali", value: "Palm Jebel Ali"  },
    { label: "Palm Jumeirah", value: "Palm Jumeirah"  },
    { label: "Pearl Jumeirah", value: "Pearl Jumeirah"  },
    { label: "Ras Al Khor", value: "Ras Al Khor"  },
    { label: "Reem", value: "Reem"  },
    { label: "Remraam", value: "Remraam"  },
    { label: "Satwa", value: "Satwa"  },
    { label: "Serena", value: "Serena"  },
    { label: "Sheikh Zayed Road", value: "Sheikh Zayed Road"  },
    { label: "Silicon Oasis", value: "Silicon Oasis"  },
    { label: "Sports City", value: "Sports City"  },
    { label: "Springs", value: "Springs"  },
    { label: "Technology Park", value: "Technology Park"  },
    { label: "TechnoPark", value: "TechnoPark"  },
    { label: "The Gardens", value: "The Gardens"  },
    { label: "The Hills", value: "The Hills"  },
    { label: "The Lakes", value: "The Lakes"  },
    { label: "The Ridge", value: "The Ridge"  },
    { label: "The Sustainable City	", value: "The Sustainable City"  },
    { label: "The Valley", value: "The Valley"  },
    { label: "The Views", value: "The Views"  },
    { label: "The Villa", value: "The Villa"  },
    { label: "The World Islands", value: "The World Islands"  },
    { label: "Tiger Woods", value: "Tiger Woods"  },
    { label: "Tilal Al Ghaf Development", value: "Tilal Al Ghaf Development"  },
    { label: "Town Square", value: "Town Square"  },
    { label: "Umm Al Sheif", value: "Umm Al Sheif"  },
    { label: "Umm Hurair", value: "Umm Hurair"  },
    { label: "Umm Ramool", value: "Umm Ramool"  },
    { label: "Umm Suqeim", value: "Umm Suqeim"  },
    { label: "Victory Heights", value: "Victory Heights"  },
    { label: "Wadi Al Amardi", value: "Wadi Al Amardi"  },
    { label: "Wasl Gate", value: "Wasl Gate"  },
    { label: "World Trade Centre", value: "World Trade Centre"  },
    { label: "Zabeel Road", value: "Zabeel Road"  },
];

const leadsourcedata = [
    { label: 'Property Finder', value: 'Property Finder' },
    { label: 'Bayut', value: 'Bayut' },
    { label: 'Dubizzle', value: 'Dubizzle' },
    { label: 'Walk-In', value: 'Walk-In' },
    { label: 'Cold Calling', value: 'Cold Calling' },
    { label: 'Facebook / Instagram', value: 'Facebook / Instagram' },
    { label: 'Google', value: 'Google' },
    { label: 'Website', value: 'Website' },
    { label: 'Referral', value: 'Referral' },
];