export const USER_STATE_CHANGE = 'USER_STATE_CHANGE'
export const USER_POSTS_STATE_CHANGE = 'USER_POSTS_STATE_CHANGE'
export const USER_KEYINFO_STATE_CHANGE = 'USER_KEYINFO_STATE_CHANGE'

export const USER_KEYINFO_DETAILS_STATE_CHANGE = 'USER_KEYINFO_DETAILS_STATE_CHANGE'